#!/bin/bash
#
# imis-connect         start/stop/status script
#
# chkconfig:  2345 64 36
# description: Console service for imis-connect
# processname: imis-connect
# config: /etc/imis-connect

IMIS_CONNECT_USER='bahmni'

imisConnectPid() {
    echo `ps -fe | grep 'imis-connect*.jar' | grep -v grep | tr -s " "|cut -d" " -f2`
}

start(){
    pid=$(imisConnectPid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService imis-connect is already running (pid: $pid)\e[00m"
    else
        /bin/su -s /bin/bash bahmni /opt/imis-connect/bin/start.sh
        echo -e "\e[00;32mStarting imis-connect\e[00m"
    fi
    return 0
}

debug() {
    pid=$(imisConnectPid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService imis-connect is already running (pid: $pid)\e[00m"
    else
        /bin/su -s /bin/bash ${IMIS_CONNECT_USER} /opt/imis-connect/bin/debug.sh
        echo -e "\e[00;32mStarting imis-connect in debug mode\e[00m"
    fi
    return 0
}
status() {
    pid=$(imisConnectPid)
    if [ -n "$pid" ];
    then
        echo -e "\e[00;32mimis-connect is running with pid: $pid\e[00m"
        exit 0
    else
        echo -e "\e[00;31mimis-connect is not running\e[00m"
        exit 3
    fi
}

stop() {
    pid=$(imisConnectPid)
    if [ -n "$pid" ];
    then
        echo -e "\e[00;31mTerminating imis-connect\e[00m"
        kill -9 ${pid}
    else
        echo -e "\e[00;31mimis-connect is not running\e[00m"
    fi
    return
}

log() {
    if [ -e /opt/imis-connect/var/log/imis-connect.log ];
    then
        tail -f /opt/imis-connect/var/log/imis-connect.log
    fi
    exit 0
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    debug)
        debug
    ;;
    restart)
        stop
        start
    ;;
    status)
        status
    ;;
    kill)
        stop
    ;;
    log)
        log
    ;;
esac