DROP DATABASE IF EXISTS INSURANCE;
CREATE DATABASE INSURANCE;

DROP TABLE IF EXISTS INSURANCE.IMIS;
CREATE TABLE `INSURANCE`.`IMIS` (
  `ITEM_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `ITEM_NAME` VARCHAR(45) NULL,
  `CATEGORY` VARCHAR(45) NULL,
  `INSURANCE_CODE` VARCHAR(45) NULL,
  `DOSING_UNITS` VARCHAR(45) NULL,
  `RATE` VARCHAR(45) NULL,
  `CREATED_DATE` DATETIME NULL,
  `UPDATED_DATE` DATETIME NULL,
  PRIMARY KEY (`ITEM_ID`));