CREATE TABLE IF NOT EXISTS FHIR_RESOURCE ( 
	id serial PRIMARY KEY not null, 
	ts TIMESTAMP, version VARCHAR(5), 
	resource_type VARCHAR(10),
	status VARCHAR(20), 
	resource JSONB );
	
CREATE TABLE IF NOT EXISTS LOGS
(
	USER_ID VARCHAR(20) NOT NULL,
	DATED   TIMESTAMP NOT NULL,
	LOGGER  VARCHAR(50) NOT NULL,
	LEVEL   VARCHAR(10) NOT NULL,
	MESSAGE VARCHAR(1000) NOT NULL

);